In [91]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import r2_score

In [84]:
veri=pd.read_csv("veri_setleri/housing.csv")
veri.head(3)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY

Şimdi pandas ile bir sütunda bulunan kategorik verilerin tekil hallerini görelim.

In [85]:
# kategorik ocean_proximity verisini sayısal veriye çvirelim
le=LabelEncoder()
veri["ocean_proximity"]=le.fit_transform(veri["ocean_proximity"])
veri["ocean_proximity"].astype("float64")
veri.dropna(inplace=True)

#veri=veri.dropna()


In [77]:
veri.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value  ocean_proximity  
0       322.0       126.0         8.3252            452600.0                3  
1      2401.0      1138.0         8.3014            358500.0                3  
2       496.0       177.0         7.2574            352100.0                3  
3       558.0       219.0         5.6431            341300.0                3  
4       565.0       259.0         3.8462            342200.0                3

In [86]:
X=veri.iloc[:,[2,3,4,5,6,7,9]].values
X

array([[4.1000e+01, 8.8000e+02, 1.2900e+02, ..., 1.2600e+02, 8.3252e+00,
        3.0000e+00],
       [2.1000e+01, 7.0990e+03, 1.1060e+03, ..., 1.1380e+03, 8.3014e+00,
        3.0000e+00],
       [5.2000e+01, 1.4670e+03, 1.9000e+02, ..., 1.7700e+02, 7.2574e+00,
        3.0000e+00],
       ...,
       [1.7000e+01, 2.2540e+03, 4.8500e+02, ..., 4.3300e+02, 1.7000e+00,
        1.0000e+00],
       [1.8000e+01, 1.8600e+03, 4.0900e+02, ..., 3.4900e+02, 1.8672e+00,
        1.0000e+00],
       [1.6000e+01, 2.7850e+03, 6.1600e+02, ..., 5.3000e+02, 2.3886e+00,
        1.0000e+00]])

In [87]:
y=veri.iloc[:,[8]].values

In [88]:
lr=LinearRegression()

In [89]:
lr.fit(X,y)

LinearRegression()

In [92]:
lr.coef_

array([[ 1.82326348e+03, -2.02661591e+01,  1.02422638e+02,
        -3.35768393e+01,  1.21021716e+02,  4.78789703e+04,
         4.36514074e+03]])

In [94]:
lr.intercept_

array([-50034.29951223])

In [96]:
y_tahmin=lr.predict(X)
karesel_hata=r2_score(y,y_tahmin)
karesel_hata

0.5695386307913364

In [98]:
x_test=[[30.0,1500.0,200.0,510.0,200.0,8.0,2]]
y_test=lr.predict(x_test)
y_test

array([[393591.09253103]])

In [99]:
x_test2=[[41.0,880.0,129.0,322.0,126.0,8.3252,3]]
y_test2=lr.predict(x_test2)
y_test2

array([[436232.22286189]])